### PR TITLE
feat: add rococo support and to the registry

### PR DESCRIPTION
**Pull request by TarikGul**
This adds rococo support to the registry

closes: https://github.com/paritytech/asset-transfer-api/issues/290

### CODE REVIEW

**Review by bee344 — APPROVED** [review]
Lgtm

**Comment by nikita-andrejevs** [comment]
Hello folks,

Seems the release is missing changes in `src/registry/findRelayChain.ts`.
There is no way to create an api instance for Rococo.

https://github.com/paritytech/asset-transfer-api/blob/main/src/registry/findRelayChain.ts#L11

**Comment by TarikGul** [comment]
@nikita-andrejevs Thanks for reporting this, I am going to get this fixed a make a small patch release. Thanks again!

**Comment by TarikGul** [comment]
@nikita-andrejevs Added in this release: https://github.com/paritytech/asset-transfer-api/releases/tag/v0.1.2

Please read the release notes as there is an important nuance to using rococo.

**Pull request merged**
